# Generated by Django 5.1 on 2024-11-01 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiApp', '0003_alter_part_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
