# Generated by Django 5.1 on 2024-11-04 16:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiApp', '0007_alter_part_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
