# Generated by Django 5.1 on 2024-11-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiApp', '0008_part_image_urls_part_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='part',
            name='price',
        ),
    ]
