# Generated by Django 5.1 on 2024-11-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiApp', '0009_remove_part_image_urls_remove_part_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
