# Generated by Django 5.1 on 2024-11-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiApp', '0010_part_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
