# Generated by Django 5.1 on 2024-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiApp', '0011_part_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
